version: '3'

services:
  db:
    image: postgres:14
    ports:
      - 5432:5432
    command: postgres -c log_statement=all
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}

volumes:
  postgres:
