version: "3"

services:
  nginx_backend:
    image: justmark0me_backend_nginx:latest
    ports:
      - 80
    depends_on:
      - backend
    networks:
      - web
      - project
    environment:
      VIRTUAL_HOST: api.justmark0.me
      LETSENCRYPT_HOST: api.justmark0.me
      LETSENCRYPT_EMAIL: developer@justmark0.me

  backend:
    image: justmark0me_backend:latest
    restart: always
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DBNAME=$POSTGRES_DBNAME
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_PORT=$POSTGRES_PORT
    ports:
      - 8080
    networks:
      - project

networks:
  web: # external network for hostname access
    external:
      name: web
  project: # internal network for project
