name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v2
      - name: Build and start docker image
        uses: actions/checkout@v2

      - name: Stop previous containers
        run: docker stop -t 3 justmark0me_backend
        continue-on-error: true

      - name: Remove old container
        run: docker rm -f justmark0me_backend
        continue-on-error: true

      - name: Build container
        run: docker build -t justmark0me_backend -f Dockerfile .  &&
          docker tag justmark0me_backend justmark0me_backend:latest

      - name: Run service
        env:
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          docker run --detach \
          --name justmark0me_backend \
          --env "VIRTUAL_PORT=8080" \
          --env "VIRTUAL_HOST=api.justmark0.me" \
          --env "LETSENCRYPT_HOST=api.justmark0.me" \
          --env "LETSENCRYPT_EMAIL=developer@justmark0.me" \
          --env "ADMIN_PASSWORD=$ADMIN_PASSWORD" \
          --env "DATABASE_URL=$DATABASE_URL" \
          justmark0me_backend:latest 
