name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v2
      - name: Build and start docker image
        uses: actions/checkout@v2

      - name: Stop previous containers
        run: docker-compose -f docker-compose.deploy.yml -p justmark0me_backend stop

      - name: Remove old container
        run: doercker-compose -f docker-compose.deploy.yml -p justmark0me_backend rm -f

      # Build containers
      - run: |
          docker build -t justmark0me_backend -f deploy/go/Dockerfile .
          docker tag justmark0me_backend justmark0me_backend:latest
          docker build -t justmark0me_backend_nginx -f deploy/nginx/Dockerfile .
          docker tag justmark0me_backend_nginx justmark0me_backend_nginx:latest

      - name: Run service
        run: docker-compose -f docker-compose.deploy.yml -p justmark0me_backend up -d

#      - name: Test
#        run: go test -v ./...
