name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v2
      - name: Build and start docker image
        uses: actions/checkout@v2

      - name: Stop previous containers
        run: docker stop -f justmark0me_backend
        continue-on-error: true

      - name: Remove old container
        run: docker rm -f justmark0me_backend
        continue-on-error: true

      - name: Build container
        run: docker build -t justmark0me_backend -f Dockerfile .  &&
          docker tag justmark0me_backend justmark0me_backend:latest

      - name: Run service
        env:
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DBNAME: ${{ secrets.POSTGRES_DBNAME }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
        run: |
          docker run --detach \
          --name justmark0me_backend \
          --env "VIRTUAL_PORT=8080" \
          --env "VIRTUAL_HOST=api.justmark0.me" \
          --env "LETSENCRYPT_HOST=api.justmark0.me" \
          --env "LETSENCRYPT_EMAIL=developer@justmark0.me" \
          --env "ADMIN_PASSWORD=$ADMIN_PASSWORD" \
          --env "POSTGRES_USER=$POSTGRES_USER" \
          --env "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" \
          --env "POSTGRES_DBNAME=$POSTGRES_DBNAME" \
          --env "POSTGRES_HOST=$POSTGRES_HOST" \
          --env "POSTGRES_PORT=$POSTGRES_PORT" \
          justmark0me_backend:latest 
